# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: bionic
cache: packages

jobs:
  include:
  - r: release
    os: linux
    env: DEPLOY="true"
  - r: release # test that the graceful failure systems work
    os: linux
    env: DEPLOY="true" URL_DOWN=TRUE
  - r: devel
    os: linux
    env: DEPLOY="false"
  - r: release
    os: osx
    osx_image: xcode11.3
    env: DEPLOY="false"

addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - libharfbuzz-dev
      - libfribidi-dev

brew_packages:
  - udunits

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  strategy: git
  provider: pages
  token: $GITHUB_PAT
  keep_history: true
  local_dir: docs
  on:
    branch: master
    condition: $DEPLOY = 'true'

r_binary_packages:
- Rcpp
- units
- devtools
- ape
- backports
- base64enc
- cellranger
- chron
- classInt
- cli
- crayon
- curl
- DBI
- digest
- e1071
- ellipsis
- evaluate
- fansi
- glue
- highr
- hms
- htmltools
- jsonlite
- knitr
- magrittr
- markdown
- mime
- pillar
- pkgconfig
- prettyunits
- progress
- R6
- readxl
- rematch
- remotes
- rlang
- rmarkdown
- sf
- stringi
- stringr
- tibble
- tinytex
- utf8
- vctrs
- xfun
- yaml
- zeallot
- assertthat

r_packages:
- pkgdown
